const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const $ = id => document.getElementById(id);
const levels = [
  {title:'The first delivery',story:'The village is waking up. Three little letters are waiting to find their doors.',map:['........','...#....','...#.#..','........','..##.#..','........','........'],start:[1,3],houses:[[1,1],[6,1],[6,5]],stamps:[[4,1],[5,5]],ink:28,colors:['#cd8d68','#d4aa60','#9aaf78']},
  {title:'The puddle parade',story:'Last night’s rain left puddles everywhere. A good post snail always knows the long way around.',map:['........','...~....','..~~.#..','...~....','..#..~..','.....~..','........'],start:[1,3],houses:[[1,1],[6,2],[6,5]],stamps:[[4,0],[3,6]],ink:29,colors:['#b98777','#c8a052','#83a3a0']},
  {title:'A note for the baker',story:'The baker has lost her favorite recipe. Thread through the thicket and make her morning.',map:['........','..#..#..','..#..#..','........','...##...','..#.....','........'],start:[1,3],houses:[[1,1],[6,1],[5,5]],stamps:[[4,0],[6,4]],ink:31,colors:['#c58b69','#ad9d69','#b57d79']},
  {title:'The last little letter',story:'One final round before sunset. The whole woodland is rooting for you, Pip.',map:['........','...~....','..#~.#..','........','..#..#..','...~....','........'],start:[1,3],houses:[[1,1],[6,1],[6,5],[2,5]],stamps:[[4,0],[4,6]],ink:34,colors:['#c89268','#a4aa75','#bb8b85','#d0aa64']}
];
let levelIndex=0,path=[],completed=0,dragging=false,lastPointer=null,soundOn=true,toastTimer;
const SIZE=70, PITCH=78, LEFT=88, TOP=72;
const key=(x,y)=>`${x},${y}`;
const same=(a,b)=>a[0]===b[0]&&a[1]===b[1];
const level=()=>levels[levelIndex];
const cell=(x,y)=>({x:LEFT+x*PITCH+SIZE/2,y:TOP+y*PITCH+SIZE/2});
const has=(arr,p)=>arr.some(q=>same(q,p));
function rounded(x,y,w,h,r,fill,stroke,line=1){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.lineWidth=line;ctx.strokeStyle=stroke;ctx.stroke()}}
function circle(x,y,r,color){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill()}
function line(x1,y1,x2,y2,color,width=2){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.stroke()}
function polygon(pts,color){ctx.beginPath();ctx.moveTo(...pts[0]);pts.slice(1).forEach(p=>ctx.lineTo(...p));ctx.closePath();ctx.fillStyle=color;ctx.fill()}
function flower(x,y,scale=1,color='#e5b77a'){for(let i=0;i<5;i++){let a=i*Math.PI*2/5;circle(x+Math.cos(a)*5*scale,y+Math.sin(a)*5*scale,3.4*scale,color)}circle(x,y,2.8*scale,'#fff0b4')}
function bush(x,y,seed){circle(x-14,y+8,15,'#789267');circle(x+10,y+9,17,'#668359');circle(x,y-5,18,'#8ba477');circle(x-4,y-7,4,'#9eb388');circle(x+13,y+2,3,'#a1b989');if(seed%3===0){circle(x-16,y,2,'#e8c28f');circle(x+13,y-10,2,'#e8c28f')}}
function pond(x,y){rounded(x-30,y-25,60,50,22,'#a8c5bc','#8eafa8',2);ctx.beginPath();ctx.ellipse(x,y,23,14,-.15,0,Math.PI*2);ctx.fillStyle='#bad2c7';ctx.fill();line(x-17,y-3,x-5,y-3,'#e4ece0',2);line(x+7,y+8,x+19,y+8,'#e4ece0',2);circle(x+24,y-18,3,'#819d68')}
function house(x,y,color,delivered){ctx.save();ctx.translate(x,y);rounded(-21,-4,42,32,4,'#fff3dc','#b9a88a',1.5);polygon([[-26,-3],[0,-24],[26,-3]],color);line(-26,-3,26,-3,'#8a7056',2);rounded(-5,8,10,20,3,'#aa876d');circle(2,18,1.3,'#f7dfaa');rounded(-16,2,9,9,2,'#c2d4bb','#9caf9e',1);rounded(7,2,9,9,2,'#c2d4bb','#9caf9e',1);if(!delivered){ctx.rotate(-.13);rounded(10,-29,19,14,2,'#fff9e9','#b77960',1.3);line(11,-28,19,-22,'#b77960',1);line(28,-28,19,-22,'#b77960',1)}else{circle(24,-19,10,'#91aa72');ctx.strokeStyle='white';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(20,-19);ctx.lineTo(23,-16);ctx.lineTo(28,-23);ctx.stroke()}ctx.restore()}
function postOffice(x,y){ctx.save();ctx.translate(x,y);rounded(-25,-8,50,38,5,'#f9e7c7','#ad9473',2);polygon([[-31,-7],[0,-30],[31,-7]],'#bb7356');line(-31,-7,31,-7,'#855b49',2);rounded(-7,6,14,24,3,'#7e9a78');circle(4,18,1.5,'#fff1cc');rounded(-20,0,11,11,2,'#dae6cd','#9aab91',1);rounded(10,0,11,11,2,'#dae6cd','#9aab91',1);line(27,-7,27,-24,'#8d795c',2);polygon([[27,-24],[44,-20],[27,-16]],'#ead4a4');ctx.restore()}
function snail(x,y){ctx.save();ctx.translate(x,y+13);ctx.fillStyle='#b6a77d';ctx.beginPath();ctx.ellipse(-1,11,22,10,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(16,6,9,13,0,0,Math.PI*2);ctx.fill();line(13,-3,12,-15,'#81765e',2.5);line(20,-3,22,-17,'#81765e',2.5);circle(12,-16,3.2,'#50544a');circle(22,-18,3.2,'#50544a');circle(12.7,-16.5,1,'white');circle(22.7,-18.5,1,'white');circle(-7,0,18,'#a96f58');circle(-7,0,13,'#cd9873');ctx.beginPath();ctx.arc(-7,0,8,-.7,Math.PI*1.6);ctx.strokeStyle='#965d4b';ctx.lineWidth=2.5;ctx.stroke();line(18,12,23,11,'#6f6556',1.5);ctx.restore()}
function draw(){const l=level();ctx.clearRect(0,0,800,700);rounded(0,0,800,700,10,'#f3eddb');
  // A scattering of quiet details outside the map.
  for(let i=0;i<26;i++){let x=(i*137+29)%800,y=(i*211+31)%700;if(x>LEFT-15&&x<LEFT+PITCH*8+12&&y>TOP-15&&y<TOP+PITCH*7+12)continue;flower(x,y,.6,i%2?'#e9cf9e':'#ddd9b4')}
  rounded(LEFT-15,TOP-15,PITCH*8-8+30,PITCH*7-8+30,16,'#d9dec4');
  for(let y=0;y<7;y++)for(let x=0;x<8;x++){let px=LEFT+x*PITCH,py=TOP+y*PITCH,t=l.map[y][x],n=x*13+y*17;rounded(px,py,SIZE,SIZE,10,t==='~'?'#d2dfd5':t==='#'?'#c7d5aa':(x+y)%2?'#f4efd9':'#f8f2df');if(t==='~')pond(px+35,py+35);else if(t==='#')bush(px+35,py+33,n);else{if(n%5===0){circle(px+18,py+48,2,'#cfcea9');circle(px+22,py+51,1.5,'#cfcea9')}if(n%7===0)flower(px+53,py+50,.6,'#e4c995');if(n%11===0){line(px+13,py+21,px+16,py+17,'#b3c29c',1.5);line(px+16,py+17,px+19,py+21,'#b3c29c',1.5)}}}
  // The trail lies under buildings and feet.
  if(path.length>1){ctx.beginPath();path.forEach((p,i)=>{let c=cell(...p);if(i===0)ctx.moveTo(c.x,c.y);else ctx.lineTo(c.x,c.y)});ctx.strokeStyle='#b5a175';ctx.lineWidth=13;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();ctx.strokeStyle='#ddc69b';ctx.lineWidth=8;ctx.stroke();for(let i=1;i<path.length;i++){let c=cell(...path[i]);circle(c.x,c.y,2.4,'#f6e7c7')}}
  l.stamps.forEach((p,i)=>{if(has(path,p))return;let c=cell(...p);ctx.save();ctx.translate(c.x,c.y);ctx.rotate(-.18);rounded(-12,-13,24,26,3,'#fff6da','#b6955b',2);rounded(-8,-9,16,18,2,'#e8bc80');flower(0,0,.7,'#fff2cb');ctx.restore()});
  l.houses.forEach((p,i)=>{let c=cell(...p);house(c.x,c.y,l.colors[i],has(path,p))});let home=cell(...l.start);postOffice(home.x,home.y);let current=cell(...path[path.length-1]);snail(current.x,current.y);
  // A hand-lettered compass and board corner flourishes.
  ctx.fillStyle='#94a17e';ctx.font='italic 15px Fraunces, Georgia, serif';ctx.fillText('N',43,50);line(48,61,48,79,'#a8b090',2);polygon([[48,56],[43,65],[53,65]],'#a8b090');ctx.font='italic 14px Fraunces, Georgia, serif';ctx.fillText('a little way through the woods',488,672);
}
function delivered(){return level().houses.filter(p=>has(path,p)).length}
function stamps(){return level().stamps.filter(p=>has(path,p)).length}
function updateStats(){let l=level();$('mailStat').textContent=`${delivered()} / ${l.houses.length}`;$('inkStat').textContent=`${l.ink-(path.length-1)} steps`;$('stampStat').textContent=`${stamps()} / ${l.stamps.length}`}
function beep(freq=520){if(!soundOn)return;try{let audio=window._audio||(window._audio=new (window.AudioContext||window.webkitAudioContext)());let osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*1.2,audio.currentTime+.1);gain.gain.setValueAtTime(.045,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.17)}catch(e){}}
function toast(message){let el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2300)}
function step(p){let l=level(),cur=path[path.length-1];if(p[0]<0||p[0]>7||p[1]<0||p[1]>6||Math.abs(p[0]-cur[0])+Math.abs(p[1]-cur[1])!==1)return false;if(l.map[p[1]][p[0]]!=='.'){toast('That way is blocked. Try another path!');return false}if(path.length>1&&same(p,path[path.length-2])){path.pop();beep(330);updateStats();draw();return true}if(has(path,p)&&!same(p,l.start)){toast('Pip cannot cross an old trail. Tap the last square to undo.');return false}if(same(p,l.start)&&delivered()<l.houses.length){toast('There are still letters to deliver!');return false}if(path.length-1>=l.ink){toast('Out of ink! Undo a step or start this route over.');return false}let oldMail=delivered(),oldStamps=stamps();path.push(p);beep(has(l.houses,p)?650:has(l.stamps,p)?720:430);updateStats();draw();if(delivered()>oldMail)toast('A letter found its home! ✉');else if(stamps()>oldStamps)toast('A bonus stamp for your collection! ✦');if(same(p,l.start)){setTimeout(win,450)}return true}
function win(){completed=Math.max(completed,levelIndex+1);try{localStorage.setItem('pipsLittlePostCompleted',completed)}catch(e){}renderDots();let last=levelIndex===levels.length-1;$('modalEyebrow').textContent=last?'THE WOODLAND THANKS YOU':'DELIVERY COMPLETE';$('modalArt').textContent=last?'✿':'✉';$('modalTitle').textContent=last?'Every letter has a way home.':'A very good day for mail.';$('modalText').textContent=last?'Pip delivered the final letter. Tomorrow, there will be new stories to carry.':'Pip made it back to the post office, and the woodland is a little brighter for it.';$('modalStamps').textContent='✦'.repeat(stamps())+'☆'.repeat(level().stamps.length-stamps());$('nextBtn').innerHTML=last?'Back to the first chapter <span>↗</span>':'Next chapter <span>→</span>';$('modal').classList.remove('hidden');beep(760)}
function loadLevel(i){levelIndex=i;path=[[...level().start]];$('levelTitle').textContent=level().title;$('boardTitle').textContent=level().title;$('levelStory').textContent=level().story;$('chapterNumber').textContent=`${String(i+1).padStart(2,'0')} / ${String(levels.length).padStart(2,'0')}`;$('modal').classList.add('hidden');updateStats();renderDots();draw()}
function renderDots(){let holder=$('levelDots');holder.innerHTML='';levels.forEach((l,i)=>{let b=document.createElement('button');b.textContent=i+1;b.title=`Chapter ${i+1}: ${l.title}`;b.setAttribute('aria-label',b.title);b.className=(i===levelIndex?'active ':'')+(i>completed?'locked':'');b.disabled=i>completed;b.onclick=()=>loadLevel(i);holder.appendChild(b)})}
function pointerCell(e){let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*800/r.width,y=(e.clientY-r.top)*700/r.height;return [Math.floor((x-LEFT)/PITCH),Math.floor((y-TOP)/PITCH)]}
function walkPointer(p){let cur=path[path.length-1];if(same(p,cur))return;if(Math.abs(p[0]-cur[0])+Math.abs(p[1]-cur[1])===1)step(p);else if(p[0]===cur[0]||p[1]===cur[1]){let dx=Math.sign(p[0]-cur[0]),dy=Math.sign(p[1]-cur[1]);let count=Math.abs(p[0]-cur[0])+Math.abs(p[1]-cur[1]);for(let i=1;i<=count;i++){if(!step([cur[0]+dx*i,cur[1]+dy*i]))break}}}
canvas.addEventListener('pointerdown',e=>{dragging=true;canvas.setPointerCapture(e.pointerId);lastPointer=[e.clientX,e.clientY];walkPointer(pointerCell(e))});canvas.addEventListener('pointermove',e=>{if(!dragging)return;let from=lastPointer||[e.clientX,e.clientY],distance=Math.hypot(e.clientX-from[0],e.clientY-from[1]);let count=Math.max(1,Math.ceil(distance/20));for(let i=1;i<=count;i++){let x=from[0]+(e.clientX-from[0])*i/count,y=from[1]+(e.clientY-from[1])*i/count;walkPointer(pointerCell({clientX:x,clientY:y}))}lastPointer=[e.clientX,e.clientY]});canvas.addEventListener('pointerup',()=>{dragging=false;lastPointer=null});canvas.addEventListener('pointercancel',()=>{dragging=false;lastPointer=null});
window.addEventListener('keydown',e=>{if(!$('modal').classList.contains('hidden'))return;let dirs={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0],w:[0,-1],s:[0,1],a:[-1,0],d:[1,0]};if(dirs[e.key]){e.preventDefault();let cur=path[path.length-1],d=dirs[e.key];step([cur[0]+d[0],cur[1]+d[1]])}if(e.key==='Backspace'&&path.length>1){e.preventDefault();path.pop();updateStats();draw()}});
$('restartBtn').onclick=()=>{loadLevel(levelIndex);toast('A fresh page for a fresh route.')};$('nextBtn').onclick=()=>loadLevel((levelIndex+1)%levels.length);$('replayBtn').onclick=()=>loadLevel(levelIndex);$('soundBtn').onclick=()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'♫':'♪';$('soundBtn').setAttribute('aria-label',soundOn?'Mute sound':'Unmute sound')};
try{completed=Math.min(levels.length,Math.max(0,Number(localStorage.getItem('pipsLittlePostCompleted'))||0))}catch(e){}loadLevel(0);
